export const taxRates = {
  Canada: {
    Alberta: [{ name: "GST", rate: 0.05 }],
    "British Columbia": [
      { name: "GST", rate: 0.05 },
      { name: "PST", rate: 0.07 },
    ],
    Manitoba: [
      { name: "GST", rate: 0.05 },
      { name: "PST", rate: 0.07 },
    ],
    "New Brunswick": [{ name: "HST", rate: 0.15 }],
    "Newfoundland and Labrador": [{ name: "HST", rate: 0.15 }],
    "Northwest Territories": [{ name: "GST", rate: 0.05 }],
    "Nova Scotia": [{ name: "HST", rate: 0.15 }],
    Nunavut: [{ name: "GST", rate: 0.05 }],
    Ontario: [{ name: "HST", rate: 0.13 }],
    "Prince Edward Island": [{ name: "HST", rate: 0.15 }],
    Quebec: [
      { name: "GST", rate: 0.05 },
      { name: "QST", rate: 0.09975 },
    ],
    Saskatchewan: [
      { name: "GST", rate: 0.05 },
      { name: "PST", rate: 0.06 },
    ],
    Yukon: [{ name: "GST", rate: 0.05 }],
  },
  "United States": {
    Alabama: [{ name: "State", rate: 0.04 }],
    Alaska: [{ name: "State", rate: 0.0 }],
    Arizona: [{ name: "State", rate: 0.056 }],
    Arkansas: [{ name: "State", rate: 0.065 }],
    California: [{ name: "State", rate: 0.0725 }],
    Colorado: [{ name: "State", rate: 0.029 }],
    Connecticut: [{ name: "State", rate: 0.0635 }],
    Delaware: [{ name: "State", rate: 0.0 }],
    Florida: [{ name: "State", rate: 0.06 }],
    Georgia: [{ name: "State", rate: 0.04 }],
    Hawaii: [{ name: "State", rate: 0.04 }],
    Idaho: [{ name: "State", rate: 0.06 }],
    Illinois: [{ name: "State", rate: 0.0625 }],
    Indiana: [{ name: "State", rate: 0.07 }],
    Iowa: [{ name: "State", rate: 0.06 }],
    Kansas: [{ name: "State", rate: 0.065 }],
    Kentucky: [{ name: "State", rate: 0.06 }],
    Louisiana: [{ name: "State", rate: 0.0445 }],
    Maine: [{ name: "State", rate: 0.055 }],
    Maryland: [{ name: "State", rate: 0.06 }],
    Massachusetts: [{ name: "State", rate: 0.0625 }],
    Michigan: [{ name: "State", rate: 0.06 }],
    Minnesota: [{ name: "State", rate: 0.06875 }],
    Mississippi: [{ name: "State", rate: 0.07 }],
    Missouri: [{ name: "State", rate: 0.04225 }],
    Montana: [{ name: "State", rate: 0.0 }],
    Nebraska: [{ name: "State", rate: 0.055 }],
    Nevada: [{ name: "State", rate: 0.0685 }],
    "New Hampshire": [{ name: "State", rate: 0.0 }],
    "New Jersey": [{ name: "State", rate: 0.06625 }],
    "New Mexico": [{ name: "State", rate: 0.05125 }],
    "New York": [{ name: "State", rate: 0.04 }],
    "North Carolina": [{ name: "State", rate: 0.0475 }],
    "North Dakota": [{ name: "State", rate: 0.05 }],
    Ohio: [{ name: "State", rate: 0.0575 }],
    Oklahoma: [{ name: "State", rate: 0.045 }],
    Oregon: [{ name: "State", rate: 0.0 }],
    Pennsylvania: [{ name: "State", rate: 0.06 }],
    "Rhode Island": [{ name: "State", rate: 0.07 }],
    "South Carolina": [{ name: "State", rate: 0.06 }],
    "South Dakota": [{ name: "State", rate: 0.045 }],
    Tennessee: [{ name: "State", rate: 0.07 }],
    Texas: [{ name: "State", rate: 0.0625 }],
    Utah: [{ name: "State", rate: 0.0485 }],
    Vermont: [{ name: "State", rate: 0.06 }],
    Virginia: [{ name: "State", rate: 0.043 }],
    Washington: [{ name: "State", rate: 0.065 }],
    "West Virginia": [{ name: "State", rate: 0.06 }],
    Wisconsin: [{ name: "State", rate: 0.05 }],
    Wyoming: [{ name: "State", rate: 0.04 }],
  },
};
